language: rust
sudo: required
dist: bionic
os: 
  - linux
  - macos
  - windows
cache: cargo
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin
  fi
script:
  - export CODECOV_TOKEN="2105f516-c175-4c35-b6ae-fc4e6a14aa58"
  - export CARGO_INCREMENTAL=0
  - RUSTFLAGS="-Ccodegen-units=1 -Cinline-threshold=0 -Coverflow-checks=off"
  - cargo clean
  - cargo build
  - ./test.sh
