language: rust
sudo: required
dist: bionic
os: 
  - linux
  - osx
cache: cargo
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - export CARGO_INCREMENTAL=0
  - RUSTFLAGS="-Ccodegen-units=1 -Cinline-threshold=0 -Coverflow-checks=off"
  - cargo clean
  - cargo build
  - ./test.sh
